target:
  file: data/pdb/3ERD.cif
  chains:
    A:
      hotspots:
      - 55
      - 59
      - 62
      - 63
      - 66
      - 70
binder_length: 80
preset: infer
n_sample: 50
n_step: 400
dtype: bf16
use_fast_ln: true
use_deepspeed_evo_attention: false
gpu_preferences:
- NVIDIA A100 80GB PCIe
- NVIDIA A100-SXM4-80GB
- NVIDIA H100 80GB HBM3
network_volume_id: exp3cnm7fj
data_center_id: US-CA-2
output_subdir: 3erd
